[programs.localnet]
mysolanaapp = "CtDdsRHXZHvYame4BZffsCkUhf2PE5FXj8FmVFFyW8K"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/honeybee/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
